// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Tools.Core.Datenzugriff.Administration.EntityMapConfig;
using Tools.Core.Models.Administration;

namespace Tools.Core.Datenzugriff.Administration.Datenzugriff.Administration
{
    public partial class AdministrationDbContext : DbContext
    {
        public AdministrationDbContext()
        {
        }

        public AdministrationDbContext(DbContextOptions<AdministrationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Customizing> Customizing { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new CustomizingConfiguration());
            modelBuilder.ApplyConfiguration(new StatusConfiguration());
            
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
