// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;

namespace Tools.Core.Models.Tools.TimeTracker
{
    public class StundenErfassung
    {
        /// <summary>
        /// PK der Tabelle
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Welche Erfassung wurde aufgenommen - Siehe Tabelle Status
        /// </summary>
        public int ErfassungsArt { get; set; }
        /// <summary>
        /// Erfassungstag
        /// </summary>
        public DateTime Erfassungsdatum { get; set; }
        /// <summary>
        /// Start der Arbeit
        /// </summary>
        public DateTime BeginnArbeit { get; set; }
        /// <summary>
        /// Ende der Arbeitszeit
        /// </summary>
        public DateTime? EndeArbeit { get; set; }
        /// <summary>
        /// Zusätzliche Notizen zum Arbeitstag
        /// </summary>
        public string Notizen { get; set; }
    }
}