// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Tools.Core.Models.Administration
{
    public class Status
    {
        public int Id { get; set; }
        /// <summary>
        /// Tabelle der gesuchten Spalte
        /// </summary>
        public string Tabelle { get; set; }
        /// <summary>
        /// Spalte, die einen Status repräsentiert
        /// </summary>
        public string Spalte { get; set; }
        /// <summary>
        /// Definierter Statuswert
        /// </summary>
        public int Status1 { get; set; }
        /// <summary>
        /// Beschreibung des Statuswert
        /// </summary>
        public string Beschreibung { get; set; }
    }
}