// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Tools.Core.Models.Tools.TimeTracker;

namespace Tools.Core.Datenzugriff.Tools.TimeTracker.EntityMapConfig
{
    public class StundenErfassungConfiguration : IEntityTypeConfiguration<StundenErfassung>
    {
        public void Configure(EntityTypeBuilder<StundenErfassung> entity)
        {
            entity.ToTable("StundenErfassungen");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).HasComment("PK der Tabelle");
            
            entity.Property(e => e.BeginnArbeit)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())")
                .HasComment("Start der Arbeit");

            entity.Property(e => e.EndeArbeit)
                .HasColumnType("datetime")
                .HasComment("Ende der Arbeitszeit");

            entity.Property(e => e.ErfassungsArt)
                .HasComment("Welche Erfassung wurde aufgenommen - Siehe Tabelle Status");

            entity.Property(e => e.Erfassungsdatum)
                .HasColumnType("date")
                .HasDefaultValueSql("(getdate())")
                .HasComment("Erfassungstag");

            entity.Property(e => e.Notizen)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasComment("Zusätzliche Notizen zum Arbeitstag");
        }
    }
}
