// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Tools.Core.Datenzugriff.Tools.TimeTracker.EntityMapConfig;
using Tools.Core.Models.Tools.TimeTracker;

namespace Tools.Core.Datenzugriff.Tools.TimeTracker
{
    public partial class TimeTrackerDbContext : DbContext
    {
        public TimeTrackerDbContext()
        {
        }

        public TimeTrackerDbContext(DbContextOptions<TimeTrackerDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<StundenErfassung> StundenErfassungen { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new StundenErfassungConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
