// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Tools.Core.Models.Administration;

namespace Tools.Core.Datenzugriff.Administration.EntityMapConfig
{
    public class StatusConfiguration : IEntityTypeConfiguration<Status>
    {
        public void Configure(EntityTypeBuilder<Status> entity)
        {
            entity.HasKey(e => e.Id);

            entity.Property(e => e.Beschreibung)
                .IsUnicode(false)
                .IsRequired()
                .HasMaxLength(75)
                .HasComment("Beschreibung des Statuswert");

            entity.Property(e => e.Spalte)
                .IsUnicode(false)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Spalte, die einen Status repräsentiert");

            entity.Property(e => e.Status1)
                .HasColumnName("Status")
                .HasComment("Definierter Statuswert");

            entity.Property(e => e.Tabelle)
                .IsUnicode(false)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Tabelle der gesuchten Spalte");
        }
    }
}
